### ISSUE TITLE
RelativeFormat.__localeData__ needs the full locale name, instead we just take the root locale

### ISSUE THREAD

**Issue by jasonmit** [yahoo/intl-relativeformat#25]
https://github.com/yahoo/intl-relativeformat/blob/master/src/core.js#L69

I believe is going to cause an issue as well for https://github.com/yahoo/react-intl/issues/78

Steps:
* Load both parsed CLDR objects into `IntlRelativeTime.__addLocaleData`
* The following will output the same:
  * `new IntlRelativeFormat('zh-hant-tw').format(new Date(new Date() - 3 * 60000));`
  * `new IntlRelativeFormat('zh').format(new Date(new Date() - 3 * 60000));`

**Comment by ericf** [comment]
This will force the issue of actually implementing a correct locale matcher instead of the simple poor-man's one we're using now. We should be able to look to the `Intl.js` polyfill for the details of the implementation.

**Comment by caridy** [comment]
... or we can use the implementation from content negotiation used by express (https://github.com/jshttp/negotiator/#accept-language-negotiation). In any case, this should probably be an abstraction.

**Comment by ericf** [comment]
@caridy We can start by writing the algorithm directly in this package since it's the only thing that will need it. Later we can decide if we want to pull it out into its own package.

**Comment by ericf** [comment]
## Tasks

I see the following being the set of things we need to do address this issue:

- [ ] Evaluate the CLDR data to determine which locales have different `field` values than the data for their corresponding root locale. We know Chinese is one, let's programmatically determine if there's others. This evaluation should start with just the data this package uses from CLDR.

- [ ] Based on the evaluation above, we need to make a decision whether Chinese is an exception, or if other languages have the difference across their sub-locales.

- [ ] Update [`grunt-extract-locale-data`](https://github.com/yahoo/grunt-extract-cldr-data) to extract the `field` data for all unique locales, not just the root locales. We'll also need to reconcile this with the `intl-messageformat` data since that _only_ applies to the root locales. The data for this package needs to include the plural functions + field data. (This may push us to making the locale resolution algorithm its own package since we'll likely need to run a similar process during the CLDR data extraction.)

- [ ] Update this package to work with more than just root locales — both when `__addLocaleData()` is called and when new instances are created.

- [ ] Implement correct locale resolution algorithm to find the best fit locale for the data we have; e.g. if the developer only loaded `zh` but is creating a new instance with `zh-Hant-TW`, should we fallback to `zh`? (Again we should follow how the built-in `Intl` libs handle this or the `Intl.js` polyfill, and we may want this to be its own package.)

**Comment by ericf** [comment]
With PR #28 all of the above tasks are completed.
